# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.6.2
  - scikit-learn=0.22.2
  - pandas=1.0.3
  - matplotlib=3.2.1
  - pip:
#     - --no-deps
#     - pip==20.2.2
    - azureml-defaults==1.1.5 --install-option="--use-deprecated=legacy-resolver"
    - azureml-dataprep[pandas,fuse]==1.4.0 --install-option="--use-deprecated=legacy-resolver"
channels:
  - conda-forge
